# Generated by Django 4.1.7 on 2023-08-20 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone_name',
            new_name='phone',
        ),
    ]
